# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Whisper AI ke audio processing ke liye ffmpeg zaroori hai
RUN apt-get update && apt-get install -y ffmpeg

RUN pip install --no-cache-dir --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]